### ISSUE TITLE
ImportError: undefined symbol associated with importing flare_pp

### ISSUE THREAD

**Issue by jmusiel** [mir-group/flare_pp#13]
Hi,

This package was working for me yesterday, I can't for the life of me figure out what might have changed. But now when I try to import flare_pp I encounter the following error:

```
Traceback (most recent call last):
  File "/home/jovyan/scripts/flare_project/transfer_flare_example.py", line 1, in <module>
    from al_mlp.ml_potentials.flare_pp_calc import FlarePPCalc
  File "/home/jovyan/al_mlp/al_mlp/ml_potentials/flare_pp_calc.py", line 2, in <module>
    from flare_pp._C_flare import Structure, NormalizedDotProduct, B2
ImportError: /opt/nvidia/hpc_sdk/Linux_x86_64/21.2/compilers/lib/libgomp.so.1: undefined symbol: __pgi_nvomp_drain_async
```

I am not at all familiar with this undefined symbol error, any advice?

**Comment by YuuuXie** [comment]
We didn't make any change to the master branch during the past two weeks, and I didn't encounter this issue before. What branch and commit were/are you using?

Also it seems that this issue is associated with openmp, not very sure but you might check if all the modules are loaded correctly

**Comment by jmusiel** [comment]
How can I check if the openmp or other modules are loaded correctly?

**Comment by YuuuXie** [comment]
Seems that your error is related to the compiler. Below are the modules that I loaded (check the bottom of `README`): 
cmake/3.17.3, python/3.6.3, gcc/9.3.0, eigen/3.3.7

with these modules loaded, I'm able to pip install and import in python.

**Comment by jmusiel** [comment]
I see, it was an issue with my path pulling up the wrong openmp libraries first. I was able to fix it by resetting my path order, thanks!
