### ISSUE TITLE
Is it possible to implement my own descriptor classes in python?

### ISSUE THREAD

**Issue by jmusiel** [mir-group/flare_pp#23]
I don't know any C++, but I would like to create a custom descriptor (like B2) to use instead, is that possible to do in python? 

Is there a class structure I could emulate in python to create my own descriptor class?

**Comment by YuuuXie** [comment]
Hi @jmusiel 

Sorry for the late response. In principle this should be possible as long as you provide the descriptors, the derivatives of descriptors, etc. as shown in https://github.com/mir-group/flare_pp/blob/master/src/flare_pp/descriptors/descriptor.h#L39-L44

These modules have python binding, so you could read/write the class variables with python list/numpy array. Our developer team has never tried using python customized descriptors though.
