### ISSUE TITLE
Errors when Compiling LAMMPS

### ISSUE THREAD

**Issue by guotaoqiu** [mir-group/flare_pp#39]
Dear all,

I am troubling compiling LAMMPS with flare_pp. It failed and I can't fix it.

I believe the errors come from the Eigen temporary library since the errors seem like structure mismatches.

I followed the _Note_ that "clone the Eigen repository, and mv eigen/Eigen /path/to/lammps/src/" but it doesn't work well.

The LAMMPS has complied successfully without flare_pp under the same environment.

Part of the errors are shown as follows:

/HOME/bin/lammps/lammps/src/Eigen/src/Core/Block.h:144:59:   required from ‘Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index) [with XprType = Eigen::Matrix<double, -1, 1>; int BlockRows = -1; int BlockCols = 1; bool InnerPanel = false; Eigen::Index = long int]’
/HOME/bin/lammps/lammps/src/Eigen/src/Core/VectorBlock.h:81:61:   required from ‘Eigen::VectorBlock<MatrixType, Size>::VectorBlock(VectorType&, Eigen::Index, Eigen::Index) [with VectorType = Eigen::Matrix<double, -1, 1>; int Size = -1; Eigen::Index = long int]’
/HOME/bin/lammps/lammps/src/Eigen/src/Core/../plugins/BlockMethods.h:1161:84:   required from ‘typename Eigen::DenseBase<Derived>::FixedSegmentReturnType<Eigen::internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase<Derived>::segment(Eigen::Index, NType) [with NType = int; Derived = Eigen::Matrix<double, -1, 1>; typename Eigen::DenseBase<Derived>::FixedSegmentReturnType<Eigen::internal::get_fixed_value<NRowsType>::value>::Type = Eigen::VectorBlock<Eigen::Matrix<double, -1, 1>, -1>; Eigen::Index = long int]’
/HOME/bin/lammps/lammps/src/compute_flare_std_atom.cpp:196:62:   required from here
/HOME/bin/lammps/lammps/src/Eigen/src/Core/Block.h:217:66: error: using invalid field ‘Eigen::internal::BlockImpl_dense<XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess>::m_xpr’
                     m_blockRows(blockRows), m_blockCols(blockCols)
gmake[2]: *** [CMakeFiles/lammps.dir/HOME/bin/lammps/lammps/src/compute_flare_std_atom.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/lammps.dir/all] Error 2
gmake: *** [all] Error 2

Hope you can help me.

Best regards,
Max Q

**Comment by YuuuXie** [comment]
@QiuGuotao which Eigen version are you using? Their master branch might not work, you might want to try versions <= 3.4

**Comment by guotaoqiu** [comment]
> @QiuGuotao which Eigen version are you using? Their master branch might not work, you might want to try versions <= 3.4

Problem solved. Thank you very much.
