### ISSUE TITLE
stress tensor

### ISSUE THREAD

**Issue by eric-yu-zhu** [mir-group/flare_pp#48]
Hi flare team, 

I have a few questions regarding stress tensor in flare:

1. What unit is used for the stress tensor?

2. What are the differences between "stress" and "stresses" (appeared in user-defined dft force model)?
   
3. Vasp and Lammps implement different convensions (sign and order) for stress tensors. Which one is used in flare?

Thanks,
Eric

**Comment by YuuuXie** [comment]
Hi @eric-yu-zhu ,

1. The unit for stress tensor is eV/A^3
2. "stress" and "stresses" should refer to the same thing. Our c++ code has been using "stresses", while the python interface especially with ASE it has been using "stress". Sorry for the confusion
3. You don't need to take care of the sign and order as long as you use ASE's parser to read those data (from lammps or vasp). ASE will convert those data into the same order and sign, and FLARE just takes care of the ASE convention

**Comment by eric-yu-zhu** [comment]
Well explained. Thanks a lot!

Eric
