### ISSUE TITLE
uncertainties

### ISSUE THREAD

**Issue by eric-yu-zhu** [mir-group/flare_pp#51]
Hi MIR team,

I have a few questions regarding uncertainties. 

1. How do I get the uncertainty of forces with SGP?
With GP, the code snippet below predicts forces as well as uncertainties
  gp_model = gp.GaussianProcess(...)
  env = env.AtomicEnvironment(atoms, 1, np.array([cutoff]))
  force_pred, force_var_pred = gp_model.predict(env, 1)
What I am looking for is an SGP version that works similarly.

2. How do I get the uncertainties of predicted energy and stress?

3. There are three types of variance: local, DTC, SOR. My understanding is that local refers to using the local energy variance for uncertainty prediction. How about DTC and SOR? Can you elaborate a little bit? When should I use them? Can you provide some reference papers?

Thank you!

Eric

**Comment by YuuuXie** [comment]
Hi @eric-yu-zhu 

1. If you use the SGP_Calculator which is an ASE Calculator, then you can create your structure as an ASE Atoms, and then attach the SGP_Calculator, then by 
```python
atoms = Atoms(...)
sgp_model = SGP_Wrapper(...)
sgp_calc = SGP_Calculator(sgp_model)
atoms.calc = sgp_calc
atoms.get_forces()
uncertainty = atoms.calc.results["stds"]
```

2. If you set the `variance_type="local"` for the `SGP_Wrapper`, then you will get a per-atom scalar which quantifies the atomic uncertainty. If you set `variance_type="DTC"`, then then you will be able to get the uncertainty for the total energy, all force and stress components.

3. You can understand the SOR and DTC are two different types of sparsification, which are highly similar, but DTC is thought to have better uncertainty than SOR. Our active learning generally uses "local". However, only DTC and SOR give you the uncertainty for energy, force and stress components. This paper gives a great overview of SGP if you are interested: https://www.jmlr.org/papers/volume6/quinonero-candela05a/quinonero-candela05a.pdf

**Comment by eric-yu-zhu** [comment]
Crystal clear and precise, thank you!

Eric
