### ISSUE TITLE
Broken link to Google Colab

### ISSUE THREAD

**Issue by CMSDAR** [mir-group/flare_pp#53]
Hi, 
I'm looking to use FLARE++, but I've noticed the link to the introductory tutorial is broken. It also wasn't quite clear from the readme file on your FLARE page whether FLARE++ was included in that repository. Is the code for FLARE++ standalone, and could you repair or post a new link?
Thank you

**Comment by YuuuXie** [comment]
Hi @CMSDAR yes flare++ is now included in the flare repo. Please see the tutorials in the flare repo readme page
